### ISSUE TITLE
cannot load 'webpack'

### ISSUE THREAD

**Issue by claudiopro** [pheuter/essential-react#21]
```
> essential-react@0.2.5 test /Users/delphine/Development/Git/pheuter/essential-react
> PHANTOMJS_BIN=./node_modules/.bin/phantomjs ./node_modules/karma/bin/karma start karma.config.js

WARN [preprocess]: Can not load "webpack"!
  TypeError: undefined is not a function
  at Plugin.notifyKarmaAboutChanges (/Users/delphine/Development/Git/pheuter/essential-react/node_modules/karma-webpack/index.js:108:15)
  at Plugin.<anonymous> (/Users/delphine/Development/Git/pheuter/essential-react/node_modules/karma-webpack/index.js:72:9)
  at Compiler.applyPlugins (/Users/delphine/Development/Git/pheuter/essential-react/node_modules/webpack/node_modules/tapable/lib/Tapable.js:26:37)
  at Watching._done (/Users/delphine/Development/Git/pheuter/essential-react/node_modules/webpack/lib/Compiler.js:78:17)
  at Watching.<anonymous> (/Users/delphine/Development/Git/pheuter/essential-react/node_modules/webpack/lib/Compiler.js:61:18)
  at Compiler.emitRecords (/Users/delphine/Development/Git/pheuter/essential-react/node_modules/webpack/lib/Compiler.js:282:37)
  at Watching.<anonymous> (/Users/delphine/Development/Git/pheuter/essential-react/node_modules/webpack/lib/Compiler.js:58:19)
  at /Users/delphine/Development/Git/pheuter/essential-react/node_modules/webpack/lib/Compiler.js:275:11
```

This is the same as https://github.com/webpack/karma-webpack/issues/70

I'm preparing a PR to upgrade `karma` to 0.13

**Comment by pheuter** [comment]
Should be closed by #22.
