### ISSUE TITLE
Unexpected reserved word

### ISSUE THREAD

**Issue by AmenRa** [pheuter/essential-react#38]
I've installed all modules but when i launch "npm run server" i got this error:

```
/Volumes/Mac Data/Users/Elias/noteshare2/server.js:1
(function (exports, require, module, __filename, __dirname) { import express from 'express';
                                                              ^^^^^^

SyntaxError: Unexpected reserved word
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at loader (/Volumes/Mac Data/Users/Elias/noteshare2/node_modules/babel-register/lib/node.js:126:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Volumes/Mac Data/Users/Elias/noteshare2/node_modules/babel-register/lib/node.js:136:7)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Volumes/Mac Data/Users/Elias/noteshare2/start.js:5:1)
    at Module._compile (module.js:409:26)
```

This is my log: 
[npm-debug.txt](https://github.com/pheuter/essential-react/files/235040/npm-debug.txt)

Any ideas?

**Comment by AmenRa** [comment]
I found the problem, i don't know why the .babelrc file haven't been downloaded along with the other files...

**Comment by rasmuszimmer** [comment]
I'm getting this exact error, although only when trying to deploy on heroku. Any idea why this happens? Clicking "Deploy to Heroku" from this repo also gives this error when running the app (it builds fine though).
