### ISSUE TITLE
Default Heroku deploy using button (without changing anything) builds but fails when running app

### ISSUE THREAD

**Issue by rasmuszimmer** [pheuter/essential-react#41]
Hi pheuter,

Great starter kit!

Clicking "Deploy to Heroku" from this repo deploys and builds fine, but accessing the actual application causes "an unexpected error". Looking at the logs from heroku it seems there is a syntax error around "import from", i.e., something regarding Babel is not configured properly for Heroku?

I'm pretty new to all this Babel/ES6/webpack/react stuff so maybe it is something I'm doing completely wrong. Thanks in advance!

**Comment by sizov** [comment]
Please see my PR #45, let me know if using `Deploy to Heroku` from my clone works for you.
See my commit for details

**Comment by nguyennb9** [comment]
I still got that error, here is my log:

```
2016-05-19T09:23:21.464170+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=essentialreact.herokuapp.com request_id=f1e7f7a0-4e3a-4849-8e03-d07965f84f88 fwd="113.161.74.19" dyno= connect= service= status=503 bytes=
2016-05-19T09:23:28.459070+00:00 heroku[web.1]: State changed from crashed to starting
2016-05-19T09:23:32.134524+00:00 heroku[web.1]: Starting process with command `npm start`
2016-05-19T09:23:34.801654+00:00 app[web.1]: 
2016-05-19T09:23:34.801681+00:00 app[web.1]: > essential-react@0.5.0 start /app
2016-05-19T09:23:34.801690+00:00 app[web.1]: > node server.js
2016-05-19T09:23:34.801691+00:00 app[web.1]: 
2016-05-19T09:23:34.887670+00:00 app[web.1]: /app/server.js:1
2016-05-19T09:23:34.887712+00:00 app[web.1]:                                                               ^^^^^^
2016-05-19T09:23:34.887714+00:00 app[web.1]: 
2016-05-19T09:23:34.887715+00:00 app[web.1]: SyntaxError: Unexpected token import
2016-05-19T09:23:34.887715+00:00 app[web.1]:     at exports.runInThisContext (vm.js:53:16)
2016-05-19T09:23:34.887716+00:00 app[web.1]:     at Module._compile (module.js:387:25)
2016-05-19T09:23:34.887725+00:00 app[web.1]:     at Object.Module._extensions..js (module.js:422:10)
2016-05-19T09:23:34.887726+00:00 app[web.1]:     at Module.load (module.js:357:32)
2016-05-19T09:23:34.887726+00:00 app[web.1]:     at Function.Module._load (module.js:314:12)
2016-05-19T09:23:34.887727+00:00 app[web.1]:     at Function.Module.runMain (module.js:447:10)
2016-05-19T09:23:34.896181+00:00 app[web.1]: 
2016-05-19T09:23:34.904671+00:00 app[web.1]: npm ERR! Linux 3.13.0-85-generic
2016-05-19T09:23:34.906143+00:00 app[web.1]: npm ERR! code ELIFECYCLE
2016-05-19T09:23:34.906295+00:00 app[web.1]: npm ERR! essential-react@0.5.0 start: `node server.js`
2016-05-19T09:23:34.906400+00:00 app[web.1]: npm ERR! Exit status 1
2016-05-19T09:23:34.906533+00:00 app[web.1]: npm ERR! 
2016-05-19T09:23:34.906852+00:00 app[web.1]: npm ERR! If you do, this is most likely a problem with the essential-react package,
2016-05-19T09:23:34.906982+00:00 app[web.1]: npm ERR! not with npm itself.
2016-05-19T09:23:34.907067+00:00 app[web.1]: npm ERR! Tell the author that this fails on your system:
2016-05-19T09:23:34.913021+00:00 app[web.1]: npm ERR! Please include the following file with any support request:
2016-05-19T09:23:34.913233+00:00 app[web.1]: npm ERR!     /app/npm-debug.log
2016-05-19T09:23:35.753922+00:00 heroku[web.1]: State changed from starting to crashed
2016-05-19T09:23:35.750224+00:00 heroku[web.1]: Process exited with status 1
```

**Comment by rasmuszimmer** [comment]
I solved it by changing the script line in package.json

from 

"server": "node start.js"

to

"start": "node start.js"

However, since I'm new to this stuff I am not sure whether it is the right way to go about it.

**Comment by rasmuszimmer** [comment]
Closed by mistake.

**Comment by ojame** [comment]
I just have a Procfile with:

`web: npm run build`
