### ISSUE TITLE
npm start fails on osx mavericks and node version 6.40.

### ISSUE THREAD

**Issue by calirails** [pheuter/essential-react#49]
I've cloned this as a starter kit. I was able to run npm install without error but running npm start, resulted int this error that I can't quite figure out what to do with logged output.
calvin@~/Documents/Safezone/Projects/fb-react/react-starter-kit$ npm start

> essential-react@0.5.0 start /Users/calvin/Documents/Safezone/Projects/fb-react/react-starter-kit
> node server.js

/Users/calvin/Documents/Safezone/Projects/fb-react/react-starter-kit/server.js:1
(function (exports, require, module, __filename, __dirname) { import express from 'express';
                                                              ^^^^^^
SyntaxError: Unexpected token import
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:528:28)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/Cellar/node/6.4.0/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v6.4.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! essential-react@0.5.0 start: `node server.js`
npm ERR! Exit status 1

**Comment by ojame** [comment]
Do you have the [.babelrc](https://github.com/pheuter/essential-react/blob/master/.babelrc) file in the root of your directory?
